/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EstimatesRouteImport } from './routes/estimates'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AutomationLogRouteImport } from './routes/automation-log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers/$customerId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatesRoute = EstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationLogRoute = AutomationLogRouteImport.update({
  id: '/automation-log',
  path: '/automation-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation-log': typeof AutomationLogRoute
  '/dashboard': typeof DashboardRoute
  '/estimates': typeof EstimatesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/register': typeof RegisterRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation-log': typeof AutomationLogRoute
  '/dashboard': typeof DashboardRoute
  '/estimates': typeof EstimatesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/register': typeof RegisterRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation-log': typeof AutomationLogRoute
  '/dashboard': typeof DashboardRoute
  '/estimates': typeof EstimatesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/register': typeof RegisterRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation-log'
    | '/dashboard'
    | '/estimates'
    | '/forgot-password'
    | '/invoices'
    | '/jobs'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/register'
    | '/customers/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation-log'
    | '/dashboard'
    | '/estimates'
    | '/forgot-password'
    | '/invoices'
    | '/jobs'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/register'
    | '/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/automation-log'
    | '/dashboard'
    | '/estimates'
    | '/forgot-password'
    | '/invoices'
    | '/jobs'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/register'
    | '/customers/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationLogRoute: typeof AutomationLogRoute
  DashboardRoute: typeof DashboardRoute
  EstimatesRoute: typeof EstimatesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvoicesRoute: typeof InvoicesRoute
  JobsRoute: typeof JobsRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  RegisterRoute: typeof RegisterRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimates': {
      id: '/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof EstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation-log': {
      id: '/automation-log'
      path: '/automation-log'
      fullPath: '/automation-log'
      preLoaderRoute: typeof AutomationLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationLogRoute: AutomationLogRoute,
  DashboardRoute: DashboardRoute,
  EstimatesRoute: EstimatesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvoicesRoute: InvoicesRoute,
  JobsRoute: JobsRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  RegisterRoute: RegisterRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
